apiVersion: batch/v1
kind: Job
metadata:
  name: test-job
spec:
  template:
    spec:
      serviceAccountName: prefect-agent
      containers:
      - name: test-container
        image: busybox:latest
        command: ["/bin/sh", "-c", "echo 'Hello from test job'"]
      restartPolicy: Never